### ISSUE TITLE
Exporter writes lowercase "i" to "ı" when exporting CanOpenNode

### ISSUE THREAD

**Issue by ihsanliturk** [CANopenNode/CANopenEditor#34]
I'm using Turkish language settings. When I try to export CanOpenNode command, it exports "identitiy" as "ıdentity". I can correct this with a simple find/replace, but it will be better corrected in the source code.

Here is the output in OD.h file: 

    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendor_ID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_Ä±dentity;

**Comment by trojanobelix** [comment]
might be fixed in ea8c040021f9dbbaeaaa311c428bb02a42605d00. Please test!

**Comment by myildirim10** [comment]
I was also having problems with Turkish characters. Namely,
- 'ı' instead of 'i'
- 'İ' instead of 'I'
- Some ".attribute = ," content being empty
- Disappearance of "define" symbols in "OD.h"

So I wrote a simple 'python' code. If you run it where your OD.c and OD.h files are, it will make the necessary changes.
You can make minor changes to the python code if there are different bugs that need to be changed.
[Bugfix_OD_Files.zip](https://github.com/CANopenNode/CANopenEditor/files/10151217/Bugfix_OD_Files.zip)

**Comment by myildirim10** [comment]
I am also having problems with Turkish characters. Namely,

- 'ı' instead of 'i'
- 'İ' instead of 'I'
- Some ".attribute = ," content being empty
- Disappearance of "define" symbols in "OD.h"

So I wrote a simple 'python' code. If you run it where your OD.c and OD.h files are, it will make the necessary changes.
You can make minor changes to the python code if there are different bugs that need to be changed.
[Bugfix_OD_Files.zip](https://github.com/CANopenNode/CANopenEditor/files/10151244/Bugfix_OD_Files.zip)

**Comment by trojanobelix** [comment]
Which version do you have tested?

**Comment by myildirim10** [comment]
> Which version do you have tested?

I tested in this version: v4.0-51-g2d9b1ad

**Comment by trojanobelix** [comment]
It makes more sense to test the actual binaries where a lot of bug are fixed.
Also this bug (hopefully).

Please give a feedback after testing the actual binaries, if your are happy with the fixes for this problem.

**Comment by trojanobelix** [comment]
Will be closed in a few days due to lack of feedback
