### ISSUE TITLE
Wrong naming for records and array

### ISSUE THREAD

**Issue by xGreenPandax** [CANopenNode/CANopenEditor#40]
With new release v4.0-102-g634dee9 i have a problem with "ODT_RECORD" and "ODT_ARRAY", because in CANopenNode/301/CO_ODinterface.c it's called "ODT_REC" and "ODT_ARR".

@Barzello

**Comment by trojanobelix** [comment]
Uuups. Using V4? Can you put some context lines lines of the created c file (OD.c/h or CO_OD.c/h)

**Comment by trojanobelix** [comment]
Got it, please try the latest bugfix branch (634dee9f6c0cd11f68106936843153c896b73711)

**Comment by xGreenPandax** [comment]
Sorry for the delay. It looks correct. Could you provide binaries?

**Comment by trojanobelix** [comment]
Yes, but it might take some days.

**Comment by trojanobelix** [comment]
Released v4.0-103-g029e57e

**Comment by CANopenNode** [comment]
It is still not fixed.
I think, the line 172 in https://github.com/CANopenNode/CANopenEditor/commit/029e57e273771e8e8d667e2cb1ade25f39ed30c4 should be:
`odObjectType = odObjectType.Substring(0, 3);`

(Source of the problem: https://github.com/robincornelius/libedssharp/commit/af4d323768b8e065ba6cd7b022a7561671cf507d#diff-d444f21db6a5f27fef9ee46f265a188fc674e24a1502b1150256ac81bf2fa2fb)

I did a quick check. Otherwise exporter to V4 seems to produce correct output.

Could you provide new binaries?

**Comment by trojanobelix** [comment]
Janez, you are absolutely right. Sorry, I must have deleted it by mistake. I will provide new binaries!

**Comment by trojanobelix** [comment]
Done, please test.

**Comment by CANopenNode** [comment]
It works, thanks.
